# Generated by Django 2.2 on 2023-02-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20230213_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=50),
        ),
    ]
