# Generated by Django 2.2 on 2023-02-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20230213_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='info',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
